version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  mono:
    executor: lighthouse-check/default
    docker:
      - image: timbru31/node-alpine-git
      - image: ianwalter/puppeteer:latest
    steps:
      - checkout
      - run: git status
      - run: npm install
      - run: npx wdio     
      - lighthouse-check/audit:
          urls: https://www.foo.software   
      - run: exit 0

workflows:
  version: 2.1
  build:
    jobs:
      - mono
