version: 2.1
jobs:
  mocha:
    docker:
      - image: ianwalter/puppeteer:latest
    steps:
      - checkout
      - run: npm install
      - run: npx wdio

workflows:
  version: 2.1
  build:
    jobs:
      - mocha
