version: 2.1
jobs:
  mocha:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm run foo

workflows:
  version: 2.1
  build:
    jobs:
      - mocha
