version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  run:
    docker:
      - image: timbru31/node-alpine-git
    steps:
      - checkout
      - run: git log
      - run: circleci step halt
  mocha:
    docker:
      - image: ianwalter/puppeteer:latest
    steps:
      - checkout
      - run: npm install
      - run: npx wdio
  lighthouse: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.foo.software

workflows:
  version: 2.1
  build:
    jobs:
      - run
      - mocha
      - lighthouse
